["Horror Settings"]
	#Enable loud jumpscare visual and audio cues.
	enableJumpscares = true
	#Frequency of Glitch attacks. Higher number means it spawns MORE often.
	#Range: 1 ~ 100
	glitchSpawnRate = 50
	#Chance (1 in X) per tick for a Clue Sign to spawn when afflicted by Dread. Lower means MORE frequent.
	#Range: 20 ~ 10000
	clueSignChance = 200
	#Allow the Fake OS Permission screen to randomly appear.
	allowFakePermissions = false
	#Allow blocks around the Glitch to become corrupted.
	enableTileGlitches = true
